### PR TITLE
set culling mode to not clip the material in the scene

### PR DESCRIPTION
**Pull request by gustavoneves12**

### CODE REVIEW

**Comment by doudou** [comment]
Please give more information about this one. The culling mode is really important when it comes to performance, I really would like to know why you switched off some and not others.

**Comment by gustavoneves12** [comment]
But, I don't want clip the objects. I will send pictures to you, because, I don't how to explain this.

**Comment by doudou** [comment]
> But, I don't want clip the objects. I will send pictures to you, because, I don't how to explain this.

So ... what you are turning off is the far/near clipping. That's already an information that would have been nice to have ;-)

IMO, you definitely do want to clip objects. In the sonar case, any object that is further than your sonar, or closer than your sonar's minimum distance don't have to be rendered. In the camera case, you have a natural "fog" (the water) that limits the distance at which you see things. Anything further ? No need to give that to the GPU for rendering. Given the kind of multi-km scenes we have, that can make a big difference.

**Comment by doudou** [comment]
(Removed my previous dumb comment)

You do clip objects. What is important would be to know what kind of clipping you have removed, and why. What is the reason this kind of clipping, in your particular case, is harmful ?

**Comment by gustavoneves12** [comment]
The first picture, I didn't set the culling and near far mode.
culling_mode0

In the other picture, the objects are not clipped beacuse I changed the culling and near far mode.
culling_mode1

I set the zNear and the zFar to define the first  and the last area that will be rendered. The other properties are used to disable the objects clipping.

**Comment by doudou** [comment]
You still don't explain _why_ you need to disable the other culling modes. OSG does nothing weird w.r.t. culling (you disable occlusion and backface culling).

Disabling those, _especially_ since we are going to have 4 scenes rendered this way (four cameras) is NOT a trivial thing. I'd like to know why it is necessary. Just "because when I do it it renders properly" is not a good-enough answer.

**Comment by gustavoneves12** [comment]
Actually, I set the properties because is the way that I found to render the scene similar to the real camera. I read about DO_NOT_COMPUTE_NEAR_FAR, but the documentation is poor. However, if I don't define this flag, the objects inside the view frustum will be clipped.

The flags osg::CullSettings::VIEW_FRUSTUM_CULLING  and osg::CullSettings::SMALL_FEATURE_CULLING don't disable the culling (I think). I am not sure, but if I set this flags, the culling will be performed only in the objects outside of the view frustum.

I found this solution in some discussion in the internet. Below you have some links:
http://forum.openscenegraph.org/viewtopic.php?t=12998
http://forum.openscenegraph.org/viewtopic.php?t=666&view=previous
https://www.mail-archive.com/osg-users@lists.openscenegraph.org/msg46927.html

In fact, I perfomed a lof of trials and error until to get the best result.

But, I think to render the camera image, we can't to clip the objects inside the view frustum. What do you think about it?

**Pull request closed without merging**
