### PR TITLE
Fix performance issues

### PR DESCRIPTION
**Pull request by doudou**
Depends on https://github.com/Brazilian-Institute-of-Robotics/gui-vizkit3d/pull/1

### CODE REVIEW

**Comment by gustavoneves12** [comment]
You removed the qt event loop. Don't we need the qt event loop anymore? Why?
I liked your solution and I already tested your changes, it's working. But I don't know why the qt widgets is working without a event loop.

**Comment by doudou** [comment]
> I liked your solution and I already tested your changes, it's working. But I don't know why the qt widgets is working without a event loop.

Because we never use a Qt widget. My guess is that you needed it because of the show_gui feature (that's why I removed it). The only thing we use Qt for is setup the link to Xorg and the GL context creation.

**Comment by doudou** [comment]
NOTE: you will have to merge all the other related PRs, otherwise people won't be able to build.

**Comment by gustavoneves12** [comment]
Ok, I am checking each package.

**Pull request merged**
