### PR TITLE
Make setCameraPose use the Rock-body frame convention

### PR DESCRIPTION
**Pull request by dbcesar**
That is X forward, Z up and Y left.

### CODE REVIEW

**Comment by doudou** [comment]
This is _NOT_ a bug. It's a convention. You change the frame convention between the Rock standard body frame to the optical frame.

Which can be discussed, and may be fine. But you really need to learn the difference.

**Comment by dbcesar** [comment]
Since ViSP  library expects the body to camera transformation and I was giving him the camera to body, it was generating the unexpected and wrong behavior on my task. That's why I called it bug, because I didn't follow the convention when I wrote the task.

**Comment by doudou** [comment]
Are we talking about the same thing ? This is vizkit3d_world. /me confused

**Comment by dbcesar** [comment]
My fault. The whole misunderstanding was because I assumed that this part of the code was doing something that it really does not. 

I think that we can close this PR without merge. 

Since I changed this part in my lasts commits, I need to come back to the state of [this](https://github.com/Brazilian-Institute-of-Robotics/gui-vizkit3d_world/blob/535586d3cc8841e198cbbea8a80cea1d7321ecb1/src/Vizkit3dWorld.cpp#L273) and make the proper changes on the undewater simulation

**Comment by dbcesar** [comment]
@doudou, now it has the same state of when Gustavo wrote the code. Not it doesn't have to deal with the optical frame but with the body frame again.

**Comment by doudou** [comment]
So, I rewrote that one in a form that make it a lot more obvious what is the actual convention used.

**Comment by dbcesar** [comment]
I've run the cameras on the simulation. All are working properly. 

Merging this.

**Pull request merged**
